- name: Check available package manager
  command: which apt-get || which dnf || which yum || which apk
  register: pkg_manager
  changed_when: false

- name: Show package manager
  debug:
    msg: "{{ pkg_manager.stdout }}"